const BASE = 'https://121248742-ui.github.io/fishing-app/images/'

const FISH_SPECIES = [
  { id:1, name:"鲫鱼", image:BASE+"crucian_carp.png", type:"底层", diet:"杂食", rarity:1, difficulty:2, months:[1,2,3,4,5,6,9,10,11,12], peakMonths:[3,4,5,10,11], habitat:"静水或缓流的中下层，水草区、芦苇丛附近，喜在水底淤泥中觅食。中国分布最广的淡水鱼，从南到北无处不在。", bait:[{name:"红虫",tier:"best"},{name:"蚯蚓",tier:"best"},{name:"蓝鲫",tier:"good"},{name:"九一八",tier:"good"},{name:"酒米",tier:"good"},{name:"麦粒",tier:"ok"}], technique:"底钓为主，子线0.4-0.6号，袖钩3-5号。打窝用酒米少量勤补。经典漂相为上顶（送漂），看到顶1-2目提竿最佳。冬天鱼口轻，需0.2-0.3号极细子线。", tips:"春钓滩、秋钓潭、冬钓阳对鲫鱼最适用。钓鲫贵在精细——线细、钩小、饵轻、漂灵。野生大板鲫可遇不可求。", record:"野生常见0.2-0.5斤，1斤以上称大板鲫，养殖鲫可达2-3斤。" },
  { id:2, name:"鲤鱼", image:BASE+"鲤鱼.png", type:"底层", diet:"杂食", rarity:1, difficulty:3, months:[4,5,6,7,8,9,10], peakMonths:[5,6,9], habitat:"水底淤泥处、深潭、水草丛中，喜在有障碍物处栖息。善于拱泥觅食，常在水面冒出一串串气泡（鱼星）。", bait:[{name:"玉米粒",tier:"best"},{name:"螺鲤",tier:"best"},{name:"红薯块",tier:"good"},{name:"颗粒饵",tier:"good"},{name:"蚯蚓",tier:"ok"},{name:"麦粒",tier:"ok"}], technique:"底钓，钓钝不钓灵。子线1.0-2.0号，伊势尼5-8号。打窝以发酵老玉米+麦粒为佳。鲤鱼有试口习惯——先轻轻碰饵再吞，漂相为缓慢黑漂。", tips:"习性谨慎，大鱼尤其狡猾。甜、香、软是鲤鱼饵料三要素。同一钓点连钓几天后鲤鱼会产生警觉，建议换位。", record:"野生常见1-5斤，10斤以上称大鲤，水库记录可达30斤以上。" },
  { id:3, name:"草鱼", image:BASE+"grass_carp.png", type:"中下层", diet:"草食", rarity:2, difficulty:2, months:[5,6,7,8,9], peakMonths:[6,7,8], habitat:"水草丰富的中下层水域，夏季活跃在中上层。喜在水草区和岸边草丛觅食。", bait:[{name:"玉米粒",tier:"best"},{name:"草叶",tier:"best"},{name:"芦苇芯",tier:"good"},{name:"薯块",tier:"good"},{name:"颗粒饵",tier:"ok"},{name:"蚂蚱",tier:"ok"}], technique:"夏季可浮钓（挂水草或芦苇叶），春秋底钓。子线1.5-3.0号，伊势尼7-10号。草鱼吃饵干脆，漂相直接黑漂。大草鱼冲劲十足，顶住前10秒就稳了。", tips:"草鱼不怕热——35°C高温其他鱼停口时草鱼照样进食。青草打窝效果显著：割一捆青草系石头扔钓点。", record:"常见3-10斤，大草鱼可达20-30斤，最大记录超50斤。" },
  { id:4, name:"鳊鱼", image:BASE+"鳊鱼.png", type:"中下层", diet:"杂食", rarity:2, difficulty:2, months:[4,5,6,7,8,9,10], peakMonths:[5,6,9], habitat:"江河湖泊中下层，喜欢水流平缓的洄水湾和深潭处集群活动。体型侧扁如菱形，游速较快。", bait:[{name:"红虫",tier:"best"},{name:"蚯蚓",tier:"best"},{name:"蓝鲫",tier:"good"},{name:"腥香饵",tier:"good"},{name:"麦麸",tier:"ok"},{name:"饭粒",tier:"ok"}], technique:"钓底或离底10-20cm。口小，用袖钩3-5号，子线0.6-1.0号。集群性强，上一条后往往连杆。漂相为缓慢上顶后横走。", tips:"肉质细嫩，口感最好的淡水鱼之一。打窝用菜籽饼+麸皮效果极佳，雾化后鳊鱼群聚不散。", record:"常见0.5-2斤，大鳊鱼可达3-5斤。" },
  { id:5, name:"鲢鱼(白鲢)", image:BASE+"silver_carp.png", type:"中上层", diet:"滤食", rarity:2, difficulty:3, months:[5,6,7,8,9], peakMonths:[6,7,8], habitat:"水域中上层开阔水面，滤食浮游植物。常成群在水面游动，受惊时跃出水面。中国四大家鱼之一。", bait:[{name:"酸味饵",tier:"best"},{name:"发酵豆渣",tier:"best"},{name:"商品鲢鳙饵",tier:"good"},{name:"麦麸发酵",tier:"good"}], technique:"浮钓为主，钓深0.5-1.5米。饵料雾化要快（3-5分钟化完），形成雾化区吸引白鲢。主线3.0-5.0号，伊势尼10-14号。", tips:"白鲢和花鲢（鳙鱼）常被统称为鲢鳙，但白鲢鳞片银白、头较小。部分水库禁钓白鲢。", record:"常见3-8斤，大个体可达15-25斤。" },
  { id:6, name:"鳙鱼(花鲢)", image:BASE+"bighead_carp.png", type:"中上层", diet:"滤食", rarity:2, difficulty:3, months:[5,6,7,8,9], peakMonths:[6,7,8], habitat:"与白鲢相似，但更偏向深水一点。滤食浮游动物为主，头大身小，剁椒鱼头原料。", bait:[{name:"臭饵",tier:"best"},{name:"发酵臭豆腐渣",tier:"best"},{name:"商品鲢鳙饵",tier:"good"},{name:"蒜味饵",tier:"good"}], technique:"浮钓钓深1-3米（比白鲢深）。花鲢偏好臭味饵料，中鱼后力量比白鲢更大更持久。", tips:"花鲢头大，剁椒鱼头顶级食材。钓花鲢饵要臭、钓要深。", record:"常见3-10斤，大花鲢可达20-40斤。" },
  { id:7, name:"翘嘴", image:BASE+"翘嘴.png", type:"中上层", diet:"肉食", rarity:3, difficulty:3, months:[3,4,5,6,9,10,11], peakMonths:[4,5,10], habitat:"湖泊水库中上层，清晨傍晚靠近岸边捕食小鱼。典型掠食者，靠视觉追击猎物。", bait:[{name:"活泥鳅",tier:"best"},{name:"小白条",tier:"best"},{name:"亮片",tier:"good"},{name:"米诺",tier:"good"},{name:"小虾",tier:"ok"}], technique:"路亚首选——清晨傍晚窗口期在水面搜索。手竿挂活饵浮钓1-2米。翘嘴攻击凶猛，咬口后猛烈洗鳃。", tips:"早口和晚口是关键词——日出前后和日落前后一小时。丹江口是中国的翘嘴圣地。", record:"常见1-3斤，大翘嘴可达10-15斤，丹江口曾出过20斤+巨翘。" },
  { id:8, name:"鳜鱼", image:BASE+"鳜鱼.png", type:"底层", diet:"肉食", rarity:4, difficulty:4, months:[4,5,6,9,10], peakMonths:[5,10], habitat:"水质清澈的江河水库底部，隐藏在石头缝、树根、桥墩等障碍物处伏击猎物。对水质要求极高。", bait:[{name:"活泥鳅",tier:"best"},{name:"活虾",tier:"best"},{name:"软虫",tier:"good"},{name:"卷尾蛆",tier:"good"},{name:"铅头钩",tier:"ok"}], technique:"路亚——铅头钩+软虫慢拖底部障碍区。活饵钓法用泥鳅或小虾底钓。背鳍尖刺有毒，取鱼务必用毛巾包裹！", tips:"西塞山前白鹭飞，桃花流水鳜鱼肥。中国最名贵淡水食用鱼之一。水质好的水库和江河才能钓到。", record:"常见0.5-2斤，大鳜鱼可达5-8斤。" },
  { id:9, name:"罗非鱼", image:BASE+"罗非鱼.png", type:"底层", diet:"杂食", rarity:2, difficulty:2, months:[4,5,6,7,8,9,10,11], peakMonths:[5,6,7,8], habitat:"温水性鱼类，15°C以上活跃。喜水底泥沙处集群，适应力极强。南方广泛归化。", bait:[{name:"冷冻饵",tier:"best"},{name:"蚯蚓",tier:"best"},{name:"肝味饵",tier:"good"},{name:"腥香商品饵",tier:"good"}], technique:"底钓，子线0.8-1.5号（罗非牙利易切线，建议加防咬线）。吃食凶猛干脆、直接黑漂。背鳍和鳃盖有尖刺，务必用毛巾包裹取鱼。", tips:"全年耐高温但怕冷，广东/海南/广西是最佳钓区。罗非鱼也吃水草和藻类，能净化水质。", record:"常见0.3-1斤，大罗非可达2-3斤。" },
  { id:10, name:"青鱼", image:BASE+"青鱼.png", type:"底层", diet:"肉食(螺类)", rarity:3, difficulty:5, months:[5,6,7,8,9], peakMonths:[6,7,8], habitat:"大江大河和大型水库深水区底部，喜螺蛳丰富的区域。四大家鱼中体型最大。", bait:[{name:"螺蛳肉",tier:"best"},{name:"田螺",tier:"best"},{name:"玉米粒",tier:"good"},{name:"颗粒饵",tier:"good"}], technique:"重装备底钓——主线5.0-8.0号，子线3.0-5.0号，伊势尼12-16号，大物竿必备。打窝用螺蛳（敲碎壳）。中鱼后持久战，遛30分钟-1小时正常。", tips:"淡水钓的终极Boss。大型水库巨青可达50-100斤。一天可能只有一口，但值了。", record:"常见5-20斤，大青鱼可达50-80斤，最大记录超200斤。" },
]

const HOT_FISH = ['鲫鱼', '鲤鱼', '草鱼', '鳊鱼', '翘嘴']

function starStr(n) { var s=''; for(var i=0;i<(n||1);i++) s+='★'; for(var i=(n||1);i<5;i++) s+='☆'; return s }
function diffStr(n) { var s=''; for(var i=0;i<(n||1);i++) s+='◆'; for(var i=(n||1);i<5;i++) s+='◇'; return s }

module.exports = { FISH_SPECIES, HOT_FISH, starStr, diffStr, BASE }
